#!/bin/bash

#Week2: passwordCheck.sh script to create a folder, create it, 
#asks for a password and store in a .txt file
#Author: Marius Bratu
#Date: 22/01/2022

#Ask for the user input for a folder name
read -rp "Please type a folder name: " folderName

#Creates a directory based on the user input
mkdir "$folderName"

#Change directory to the folder created by user
cd "../Week2/$folderName"

#Ask for the user input for a password
read -rsp "Please type a password: " password 

#Add the user input (password) to the file secret.txt
echo Your password is: "$password" > secret.txt